version: '2'
services:
  routeventregister-app:
    image: routeventregister
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://routeventregister-postgresql:5432/RouteventRegister
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  routeventregister-postgresql:
    extends:
      file: postgresql.yml
      service: routeventregister-postgresql
